### PR TITLE
Fix: Move db init to rsmanage.

### PR DESCRIPTION
**Pull request by bjones1**
Part of getting the container build (docker-tools build) working again.

### CODE REVIEW

**Comment by bjones1** [comment]
Finally! CI is running again for the bookserver, plus a few tweaks that will make the docker-tools build process work.

**Comment by bnmnetp** [comment]
Trying to get this to run on a --single-dev build.  But I'm getting this on startup.  I have done a poetry install on bookserver to make sure everything in the new poetry.lock file is installed.  I have run poetry build and poetry install.

```
runestoneserver-runestone-1  | Installing dependencies from lock file
runestoneserver-runestone-1  | Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
runestoneserver-runestone-1  | 
runestoneserver-runestone-1  |   RuntimeError
runestoneserver-runestone-1  | 
runestoneserver-runestone-1  |   [BUG]  bookserver (1.0.8) is not satisfied.
runestoneserver-runestone-1  | 
runestoneserver-runestone-1  |   at /usr/local/venv/lib/python3.9/site-packages/poetry/mixology/partial_solution.py:200 in satisfier
runestoneserver-runestone-1  |       196│             # As soon as we have enough assignments to satisfy term, return them.
runestoneserver-runestone-1  |       197│             if assigned_term.satisfies(term):
runestoneserver-runestone-1  |       198│                 return assignment
runestoneserver-runestone-1  |       199│ 
runestoneserver-runestone-1  |     → 200│         raise RuntimeError("[BUG] {} is not satisfied.".format(term))
runestoneserver-runestone-1  |       201│ 
runestoneserver-runestone-1  |       202│     def satisfies(self, term):  # type: (Term) -> bool
runestoneserver-runestone-1  |       203│         return self.relation(term) == SetRelation.SUBSET
runestoneserver-runestone-1  |       204│ 
runestoneserver-runestone-1  | 
runestoneserver-runestone-1  | Traceback (most recent call last):
runestoneserver-runestone-1  |   File "/srv/web2py/applications/runestone/docker/docker_tools.py", line 316, in build
runestoneserver-runestone-1  |     _build_phase_2_core(build_config, arm, pic24, rust, tex)
runestoneserver-runestone-1  |   File "/srv/web2py/applications/runestone/docker/docker_tools.py", line 810, in _build_phase_2_core
runestoneserver-runestone-1  |     run_poetry(build_config.is_dev())
runestoneserver-runestone-1  |   File "/srv/web2py/applications/runestone/docker/docker_tools.py", line 1009, in run_poetry
runestoneserver-runestone-1  |     xqt(
runestoneserver-runestone-1  |   File "/srv/web2py/applications/runestone/docker/../tests/ci_utils.py", line 67, in xqt
runestoneserver-runestone-1  |     cp = subprocess.run(
runestoneserver-runestone-1  |   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
runestoneserver-runestone-1  |     raise CalledProcessError(retcode, process.args,
runestoneserver-runestone-1  | subprocess.CalledProcessError: Command 'poetry install' returned non-zero exit status 1.
runestoneserver-runestone-1  | Failed to start the Runestone servers.
runestoneserver-runestone-1  | =-=-= Runestone setup finished =-=-=
```

going back to the main branch and doing poetry install restores operations.

any ideas?

**Comment by bnmnetp** [comment]
To use this with RunestoneServer do have to be using your draft PR on the server ?

**Comment by bjones1** [comment]
Yes, the docker-tools build requires https://github.com/RunestoneInteractive/RunestoneServer/pull/1835 plus this PR to work.

**Comment by bjones1** [comment]
I haven't needed to run `poetry-fix` manually in my dev work.

**Comment by bnmnetp** [comment]
OK, thanks.  I will try them together tomorrow!

**Comment by bjones1** [comment]
Merged in 3531a468.

**Pull request closed without merging**
