### PR TITLE
Python check endpoint

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
Server endpoint to get pyflakes output from code sample

Question:
Are you happy with the endpoint being in /ns/books/?
Should it be in some new group? (/ns/utils/python_check/ or something like that)

### CODE REVIEW

**Comment by bnmnetp** [comment]
when you asked before I was not thinking about this particular thing as having a home in books.  
I am thinking that we might want to put this in its own file under routers.   Maybe `coach.py`
`/ns/coach/python_check` ?

**Comment by ascholerChemeketa** [comment]
Yes, that makes sense. Will move and update PR.

**Comment by ascholerChemeketa** [comment]
Endpoint moved

**Review by bnmnetp — APPROVED** [review]

**Comment by bnmnetp** [comment]
@ascholerChemeketa Can you run `black` on coach.py please?

**Comment by bnmnetp** [comment]
Nevermind, I can do it just as easy.

**Pull request merged**
